# Generated by Django 3.2 on 2023-09-21 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0012_facturaproveedor_pagado'),
        ('bancos', '0001_initial'),
        ('pagos', '0013_mediopago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devengamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numerocheque', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.banco')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturaproveedor')),
                ('mediopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.mediopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Devengamientos',
            },
        ),
    ]
