# Generated by Django 3.2 on 2024-06-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devengamientos', '0002_alter_devengamiento_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devengamiento',
            unique_together=set(),
        ),
    ]
