# Generated by Django 3.2 on 2023-08-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='estadopago',
            field=models.CharField(choices=[('PG', 'Pagado'), ('CC', 'Cuenta Corriente')], default='PG', max_length=2),
        ),
    ]
