# Generated by Django 3.2 on 2023-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_detallefactura_estadopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubro',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='estadopago',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('CUENTA CORRIENTE', 'Cuenta Corriente')], default='PAGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='unidad',
            field=models.CharField(choices=[('Metro Cubico', 'Metro Cubico'), ('Metro Cuadrado', 'Metro Cuadrado'), ('Unidad', 'Unidad'), ('Litro', 'Litro')], default='Unidad', max_length=20),
        ),
    ]
