# Generated by Django 3.2 on 2023-09-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_auto_20230905_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.obra', unique=True),
        ),
    ]
