# Generated by Django 3.2 on 2023-09-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_factura_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.obra'),
        ),
    ]
