# Generated by Django 3.2 on 2023-09-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('pagos', '0008_alter_factura_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.banco'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombrefantasia',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razonsocial',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
