# Generated by Django 3.2 on 2023-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_auto_20230913_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
