# Generated by Django 3.2 on 2023-09-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0010_proveedor_cuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cbu',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cuit',
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='ProveedorBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionbanco', models.CharField(blank=True, max_length=100, null=True)),
                ('cbu', models.CharField(max_length=200, unique=True)),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.proveedor')),
                ('tipocuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.tipocuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores Bancos',
            },
        ),
    ]
