# Generated by Django 3.2 on 2024-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_obra_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='comitente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='licitacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
