# Generated by Django 3.2 on 2024-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_auto_20240127_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
