# Generated by Django 3.2 on 2024-03-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificio',
            old_name='direcciones',
            new_name='direccion',
        ),
    ]
