# Generated by Django 3.2 on 2024-03-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_rename_direcciones_edificio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='monto_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
