# Generated by Django 3.2 on 2024-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_recibo_monto_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='apellido',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
