# Generated by Django 3.2 on 2024-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0004_auto_20240307_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='monto',
        ),
        migrations.AddField(
            model_name='departamento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
