# Generated by Django 3.2 on 2024-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0006_contrato_cuotacontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotacontrato',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
