# Generated by Django 3.2 on 2024-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0009_auto_20240315_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
