# Generated by Django 3.2 on 2024-09-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0011_auto_20240415_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='inquilino_apellido',
            new_name='inquilinoapellido',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='inquilino_dni',
            new_name='inquilinodni',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='inquilino_nombre',
            new_name='inquilinonombre',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='nombre',
        ),
    ]
