# Generated by Django 3.2 on 2023-10-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratistas', '0001_initial'),
        ('pagos', '0013_mediopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerrado', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.obra')),
            ],
            options={
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.contratista')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name_plural': 'Detalle Presupuestos',
            },
        ),
    ]
