# Generated by Django 3.2 on 2023-10-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_mediopago'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('id', 'obra')},
        ),
    ]
