# Generated by Django 3.2 on 2023-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_auto_20231028_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
