# Generated by Django 4.0.6 on 2023-10-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_detallepresupuesto_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
