# Generated by Django 3.2 on 2023-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_detallepresupuesto_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
