# Generated by Django 3.2 on 2023-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_alter_detallepresupuesto_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuesto',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
