# Generated by Django 3.2 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_auto_20231117_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuesto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
