# Generated by Django 3.2 on 2024-08-21 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_obra_finalizada'),
        ('presupuestos', '0007_detallepresupuesto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.obra', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=set(),
        ),
    ]
