# Generated by Django 3.2 on 2025-07-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_alter_presupuesto_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='entregado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
