# Generated by Django 3.2 on 2023-09-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0001_initial'),
        ('personal', '0002_auto_20230923_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratistas.contratista'),
        ),
    ]
