# Generated by Django 3.2 on 2023-10-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_personal_contratista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='fechabaja',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='fechaingreso',
        ),
        migrations.AddField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AltaBajaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alta', models.DateField()),
                ('baja', models.DateField(blank=True, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'verbose_name_plural': 'Altas Bajas Personal',
            },
        ),
    ]
