# Generated by Django 3.2 on 2023-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_quincena_quincenadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cuil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
