# Generated by Django 3.2 on 2023-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_personal_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
