# Generated by Django 3.2 on 2023-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_personal_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='domicilio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
