# Generated by Django 3.2 on 2023-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rodados',
            },
        ),
    ]
