# Generated by Django 3.2 on 2024-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodados', '0004_alter_rodado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodado',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
