# Generated by Django 3.2 on 2023-09-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0008_alter_factura_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoBruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Ingresos Brutos',
            },
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'IVA',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('preciounitario', models.DecimalField(decimal_places=4, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=4, max_digits=20)),
                ('descuentoporcentaje', models.DecimalField(decimal_places=4, max_digits=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturaproveedor')),
                ('ingresosbrutos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.ingresobruto')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.iva')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.obra')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.rubro')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.unidad')),
            ],
            options={
                'verbose_name_plural': 'Detalles Facturas',
            },
        ),
    ]
