# Generated by Django 3.2 on 2023-09-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_factura_obra'),
        ('facturas', '0003_alter_facturaproveedor_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.proveedor'),
        ),
    ]
