# Generated by Django 3.2 on 2023-09-15 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturas', '0005_detallefacturaproveedor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripciondetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciondetalle', models.CharField(max_length=100, unique=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.unidad')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='descripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.descripciondetalle'),
        ),
    ]
