# Generated by Django 3.2 on 2023-09-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_auto_20230915_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefacturaproveedor',
            old_name='descripcion',
            new_name='descripciondetalle',
        ),
    ]
