# Generated by Django 3.2 on 2023-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_alter_descripciondetalle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='ajuste',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
