# Generated by Django 3.2 on 2023-09-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodados', '0004_alter_rodado_usuario'),
        ('facturas', '0010_auto_20230918_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='rodado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodados.rodado'),
        ),
    ]
