# Generated by Django 3.2 on 2023-09-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_detallefacturaproveedor_rodado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
