# Generated by Django 3.2 on 2023-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_facturaproveedor_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='pagoparcial',
            field=models.BooleanField(default=False),
        ),
    ]
