# Generated by Django 3.2 on 2023-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0013_facturaproveedor_pagoparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='descuentoglobal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='preciocepcionglobal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
