# Generated by Django 3.2 on 2023-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_auto_20230926_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='ajusteglobal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
