# Generated by Django 3.2 on 2023-09-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0015_facturaproveedor_ajusteglobal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='ingresosbrutos',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='iva',
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='ingresosbrutos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.ingresobruto'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='iva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
    ]
