# Generated by Django 3.2 on 2023-10-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0018_detallefacturaproveedor_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='iva',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
    ]
