# Generated by Django 3.2 on 2023-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0019_alter_facturaproveedor_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='preciototal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
