# Generated by Django 3.2 on 2024-05-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_obra_finalizada'),
        ('facturas', '0022_alter_facturaproveedor_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='ingresosbrutos',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='iva',
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='ingresosbrutos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.ingresobruto'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='iva',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.proveedor'),
        ),
    ]
