# Generated by Django 3.2 on 2024-06-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_obra_finalizada'),
        ('facturas', '0023_auto_20240531_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturaproveedor',
            unique_together={('comprobante', 'proveedor')},
        ),
    ]
